CREATE OR REPLACE TRIGGER trg_notifications_id
BEFORE INSERT ON NOTIFICATIONS
FOR EACH ROW
BEGIN
    SELECT notifications_seq.NEXTVAL
    INTO :NEW.id
    FROM dual;
END;

CREATE INDEX IDX_NOTI_USER ON NOTIFICATIONS(USER_NUMBER);
CREATE INDEX IDX_NOTI_SENT ON NOTIFICATIONS(SENT);
CREATE INDEX IDX_NOTI_READ ON NOTIFICATIONS(READ);