create or replace TRIGGER after_book_record_insert
after INSERT ON book_record
FOR EACH ROW

BEGIN
-- BOOKINFO 업데이트
UPDATE BOOKINFO
SET
BOOKCOUNT = BOOKCOUNT + 1
WHERE BOOKNUMBER = :NEW.BOOKNUMBER;

-- USERINFO 업데이트
UPDATE USERINFO
SET
    USERCANBORROW = USERCANBORROW + 1
WHERE USERNUMBER = :NEW.USERNUMBER;

END;